name: rl
channels:
    - conda-forge
    - pytorch
dependencies:
    - python=3.9
    - numpy=1.19.*
    - matplotlib=3.3.*
    - gym=0.18.*
    - gym-all=0.18.*
    - gym-classic_control=0.18.*
    - gym-box2d=0.18.*
    - gym-atari=0.18.*
    - pytorch=1.7.*
